name: Tests

on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.2]
        laravel: [11.*, 10.*]
        dependency-version: [prefer-stable]
        testsuite: [core, admin, shipping, stripe]
        extend-models: ["true", "false"]
        include:
          - laravel: 11.*
            testbench: 9.*
          - laravel: 10.*
            testbench: 8.*
    name: ${{ matrix.testsuite }} - PHP ${{ matrix.php }} - L${{ matrix.laravel }} ${{ matrix.dependency-version == 'prefer-lowest' && '↓' || '↑' }} ${{ matrix.extend-models == 'true' && 'E' || '' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-p${{ matrix.php }}-l${{ matrix.laravel }}-${{ hashFiles('composer.json') }}
          restore-keys: composer-p${{ matrix.php }}-l${{ matrix.laravel }}-
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, pdo_sqlite
          coverage: none
      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist
      - name: Execute tests
        env:
          APP_ENV: testing
          DB_CONNECTION: testing
          DB_DATABASE: ":memory:"
          LUNAR_TESTING_REPLACE_MODELS: ${{ matrix.extend-models }}
        run: ./vendor/bin/pest --testsuite ${{ matrix.testsuite }}
